apiVersion: apps/v1          #A
kind: Deployment
metadata:
  name: gitopbook
spec:
  template:
    spec:
      containers:
      - name: gitopbook     #B
        env:                 #C
        - name: DEBUG
          value: "true"
