apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:                        #A
- ../../base

patchesStrategicMerge:
- debug.yaml                  #B

images:                       #C
- name: rudiheydra/gitopbook
  newTag: v0.2